app:
  secret_token: <%= Dotcloud.env["SECRET_TOKEN"] %>
  cookie_key: "_rails_france_session"
devise:
  pepper: <%= ENV["PEPPER"] %>
mailer:
  host: "railsfrance.org"
  from: "RailsFrance"
aws_ses:
  access_key_id: <%= ENV["ACCESS_KEY_ID"] %>
  secret_access_key: <%= Dotcloud.env["SECRET_ACCESS_KEY"] %>
redis:
  host: <%= Dotcloud.env["DOTCLOUD_REDIS_REDIS_HOST"] %>
  port: <%= Dotcloud.env["DOTCLOUD_REDIS_REDIS_PORT"] %>
  login: <%= Dotcloud.env["DOTCLOUD_REDIS_REDIS_LOGIN"] %>
  password: <%= Dotcloud.env["DOTCLOUD_REDIS_REDIS_PASSWORD"] %>
  db: 1
  expire_view: 86400
  expire_tweet: 3600
twitter:
  account: <%= Dotcloud.env['TWITTER_ACCOUNT'] %>
  consumer_key: <%= Dotcloud.env['TWITTER_CONSUMER_KEY'] %>
  consumer_secret: <%= Dotcloud.env['TWITTER_CONSUMER_SECRET'] %>
  oauth_token: <%= Dotcloud.env['TWITTER_OAUTH_TOKEN'] %>
  oauth_token_secret: <%= Dotcloud.env['TWITTER_OAUTH_TOKEN_SECRET'] %>
recaptcha:
  public_key: <%= Dotcloud.env['RECAPTCHA_PUBLIC_KEY'] %>
  private_key: <%= Dotcloud.env['RECAPTCHA_PRIVATE_KEY'] %>
api:
  meetup:
    key: <%= Dotcloud.env['MEETUP_KEY'] %>